### ISSUE TITLE
how start project

### ISSUE THREAD

**Issue by 1576523593** [rongcloud/sealrtc-web#1]

**Comment by YongHao0** [comment]
直接启动 src/index.html 即可(需使用 localhost 或 https 访问)

**Comment by YongHao0** [comment]
> 直接启动 src/index.html 即可(需使用 localhost 或 https 访问)

另外需修改 src/config.js 配置项
appkey 需从融云开发者后台获取
server 需要您按照以下文档启动:
    https://github.com/rongcloud/sealrtc-server
